### PR TITLE
Fix behaviour of listxattr

### PR DESCRIPTION
**Pull request by claunia**
As per `LISTXATTR(2)`:

If  size  is  specified  as zero, these calls return the current size of the list of extended attribute names (and leave list unchanged).  This can be used to determine the size of the buffer that should be supplied in a subsequent call.  (But, bear in mind
       that there is a possibility that the set of extended attributes may change between the two calls, so that it is still necessary to check the return status from the second call.)

### CODE REVIEW

**Comment by alhimik45** [comment]
Thank you for PR. I'll investigate it soon and merge.

**Comment by alhimik45** [comment]
I found that there was refactoring such that return values are used only for errors. For returning additional info introduced `out bytesWritten` param. So your fix isn't ideologically correct :). Seems there are just missed `else` statement before next `if`

**Comment by alhimik45** [comment]
fixed code and published new version

**Comment by claunia** [comment]
Ok, well the new version makes getfattr be happy so thanks a lot! :D

**Pull request closed without merging**
